services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: MyN3wP4ssw0rd
      MYSQL_PASSWORD: MyN3wP4ssw0rd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URI: mysql+pymysql://root:MyN3wP4ssw0rd@db/classifier_db?charset=utf8mb4
      FLASK_SECRET_KEY: superstructure
      JWT_SECRET_KEY: superstructure
      ENCRYPTION_KEY: bQZFNq29Mg1JgghbNxdzDjEN7PfdYeGoBlDtjKMQS9U=

volumes:
  db_data: