apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: meli-web
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: xtaku/meli:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: flask-app-secrets
              key: DATABASE_URI
        - name: FLASK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: flask-app-secrets
              key: FLASK_SECRET_KEY
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: flask-app-secrets
              key: JWT_SECRET_KEY
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: flask-app-secrets
              key: ENCRYPTION_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - name: log-volume
          mountPath: /app/logs
      volumes:
      - name: log-volume
        emptyDir: {}
