apiVersion: v1
kind: Service
metadata:
  namespace: meli-web
  name: flask-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: flask-app
